var key = "value"


switch (key) {
    case "value":
        console.log("matches");
        break;

    case "hello":
        console.log("not matches");
        break;


    default:
        console.log("default");
        break;
}

// // Loops Example
// for (var i=0; i<=5; i++){
//     console.log("I inside", i);
// }
// console.log("I outside", i);



// ***While Loops
// var a =5 
// var b =8
// while (a<b) {
//     console.log( "a is less", a);
//     a++
// }


// ****Do While loop




